---
title: "Biomath HW1"
author: "Maxwell Greene"
date: "January 29, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Problem #1
$$
\begin{aligned}
N_{t+1}&= \rho N_t \\
N_{t'} &= \rho N_{t'-1} \\
       &= \rho (\rho N_{t'-2}) \\
       &= \rho ^{t'}N_{t'-t'} \\
       &= \rho ^{t'}N_0
\end{aligned}
$$

#Problem #2

$$
\begin{split}
  \text{For } &0 < \rho < 1 \text{:} \\
  N_t &= \rho ^t N_0 \\
  \lim_{t \to \infty} N_t &= \lim_{t \to \infty} \rho ^t N_0 \\
  N_\infty &= 0 * N_0 \\
  N_\infty &= 0
\end{split}
    \quad \quad \quad 
\begin{split}
  \text{For } & \rho > 1 \text{:} \\
  N_t &= \rho ^t N_0 \\
  \lim_{t \to \infty} N_t &= \lim_{t \to \infty} \rho ^t N_0 \\
  N_\infty &= \infty * N_0 \\
  N_\infty &= \infty \\
\end{split}
$$

#Problem #3
Considering the following simplistic population model,
$$
\frac{dN}{dt}=rN, N(0)=N_0
$$
there are several pros and cons. First, it is simple and computationally efficient; we can easily determine a solution by hand and determine the population or rate of change for any given $t$. It also models a continuously growing population, which is biologically accurate for certain populations. However, it is not able to account for the dynamics of many (possibly most) populations that have limits like a carrying capacity or a non-zero death rate. 

#Problem #4

Use the Method of separation to solve the IVP:
$$
\frac{dN}{dt}=rN, N(0) = N_0 \\ 
\begin{aligned}
  \frac{dN}{dt} &= rN \\
  \frac{1}{N}dN &= r * dt \\
  \int \frac{1}{N}dN &= \int r * dt \\
  \log N &= rt +c \\
  N &= e^ce^{rt} \\
  N(0) = N_0 &= e^ce^{r(0)} = e^c \\
  \text{Finally: } N(t) &= N_0e^{rt}
\end{aligned}
$$

#Problem #5
Consider the logistic growth model:
$$
\frac{dN}{dt}=r \Big( 1-\frac{N}{K}\Big)N, N(0)=N_0.
$$
##(a)
When is $N(t)$ increasing/decreasing?  
Increasing when $r \Big( 1-\frac{N}{K}\Big) > 1$, decreasing when $r \Big( 1-\frac{N}{K}\Big) < 1$. 

$$
\begin{split}
  \text{For the }&\text{increasing case:} \\
  1 &< r \Big( 1-\frac{N}{K}\Big) \\
  \frac{1}{r} &< 1-\frac{N}{K} \\
  \frac{1}{r} - 1 &< -\frac{N}{K} \\
  K\Big( 1-\frac{1}{r}\Big) &> N \\
  \text{Equivalently, } N&< K\Big(\frac{r-1}{r}\Big)
\end{split}
    \quad \quad \quad 
\begin{split}
  \text{For the }&\text{decreasing case:} \\
  1 &> r \Big( 1-\frac{N}{K}\Big) \\
  \frac{1}{r} &> 1-\frac{N}{K} \\
  \frac{1}{r} - 1 &> -\frac{N}{K} \\
  K\Big( 1-\frac{1}{r}\Big) &< N \\
  \text{Equivalently, } N&> K\Big(\frac{r-1}{r}\Big)
\end{split}
$$

##(b)
The rate of change of the population is zero when $\frac{dN}{dt}=0$. Assuming $r,K,N \neq 0$:
$$
\begin{aligned}
0 &= r\Big(1-\frac{N}{K}\Big) \\
\text{Since } r\neq 0, \quad 0 &= 1-\frac{N}{K} \\
1 &= \frac{N}{K}, \boxed{N=K}
\end{aligned}
$$















